# Generated by Django 3.0.4 on 2020-03-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomHome', '0002_auto_20200318_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonregulartransaction',
            old_name='time',
            new_name='date',
        ),
    ]
