# Generated by Django 2.2.12 on 2020-04-04 17:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CustomHome', '0003_auto_20200318_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetinfo',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Education', 'Education'), ('Travel', 'Travel'), ('Restaurant & Bars', 'Restaurant & Bars'), ('Bills & Utilities', 'Bills & Utilities'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Gas', 'Gas'), ('Misc', 'Misc')], max_length=255),
        ),
        migrations.AlterField(
            model_name='nonregulartransaction',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Education', 'Education'), ('Travel', 'Travel'), ('Restaurant & Bars', 'Restaurant & Bars'), ('Bills & Utilities', 'Bills & Utilities'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Gas', 'Gas'), ('Misc', 'Misc')], max_length=255),
        ),
        migrations.AlterField(
            model_name='regulartransaction',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Education', 'Education'), ('Travel', 'Travel'), ('Restaurant & Bars', 'Restaurant & Bars'), ('Bills & Utilities', 'Bills & Utilities'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Gas', 'Gas'), ('Misc', 'Misc')], max_length=255),
        ),
        migrations.CreateModel(
            name='CustomProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
